configurations:
  username: asccpusher
  password_hash: $2a$10$Dfxzu56RtsACQHU/m26WtuQla/f7DKlgGIsVzR5yAgNadg230qX9O
  password_salt: $2a$10$Dfxzu56RtsACQHU/m26Wtu

projects:
  git-test:
    id: git-test
    name: Testing Git
    dev_url: http://test.local
    test_url: http://pre.local
    production_url: http://pro.local
    dev_repo: /storage/git/git-test
    master_repo: /storage/git/git-test.git
    test_repo: /storage/git/git-test-preview
    production_repo: /storage/git/git-test-pro